### Cria uma meta
POST http://localhost:3333/goals HTTP/1.1
content-type: application/json

{
  "title": "Nadar",
  "desiredWeeklyFrequency": 2
}

### Retorna as metas pendentes
GET http://localhost:3333/pending-goals HTTP/1.1

### Cria uma meta
POST http://localhost:3333/completions HTTP/1.1
content-type: application/json

{
  "goalId":"um4spgjb54mb3n1qhxr9ka6s"
}

### Retorna o resumo das metas
GET http://localhost:3333/summary HTTP/1.1